In [2]:
import numpy as np
import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt
import pymongo

sns.set(style='ticks')
client = pymongo.MongoClient("mongodb+srv://admin:admin@cluster0-8vzpx.gcp.mongodb.net/test?retryWrites=true&w=majority")
database = client.unemployment_data
homeless1 = database.homeless1
homeless2 = database.homeless2

In [4]:
homeless1_data = pd.DataFrame(list(homeless1.find()))
homeless2_data = pd.DataFrame(list(homeless2.find()))

In [34]:
# homeless1_data.insert(0, 'id', range(0, len(homeless1_data)))
# homeless2_data.insert(0, 'id', range(0, len(homeless2_data)))

In [53]:
# homeless1_data = homeless1_data.drop('index', axis=1)
homeless1_data

,id,_id,CoC Number,CoC Name,CoC Category,Overall Homeless 2019,Overall Homeless - Under 18 2019,Overall Homeless - Age 18 to 24 2019,Overall Homeless - Over 24 2019,Overall Homeless - Female 2019,...,Overall Homeless - Transgender 2019,Overall Homeless - Gender Non-Conforming 2019,"Overall Homeless - Non-Hispanic/Non-Latino, 2019","Overall Homeless - Hispanic/Latino, 2019","Overall Homeless - White, 2019","Overall Homeless - Black or African American, 2019","Overall Homeless - Asian, 2019","Overall Homeless - American Indian or Alaska Native, 2019",Overall Homeless - Native Hawaiian or Other Pacific Islander 2019,Overall Homeless - Multiple Races 2019
0,0,5e52b003ef313cd4b609cf81,AK-500,Anchorage CoC,Other Largely Urban CoC,1111,193,132,786,422,...,4,0,1,047,64,333,140,18,439,64
1,1,5e52b003ef313cd4b609cf82,AK-501,Alaska Balance of State CoC,Largely Rural CoC,796,142,72,582,339,...,2,3,755,41,334,24,18,325,9,86
2,2,5e52b003ef313cd4b609cf83,AL-500,Birmingham/Jefferson St. Clair Shelby Counties...,Largely Suburban CoC,981,108,72,801,358,...,1,0,958,23,319,633,1,12,3,13
3,3,5e52b003ef313cd4b609cf84,AL-501,Mobile City & County/Baldwin County CoC,Other Largely Urban CoC,505,110,18,377,216,...,0,0,491,14,181,298,1,8,1,16
4,4,5e52b003ef313cd4b609cf85,AL-502,Florence/Northwest Alabama CoC,Largely Rural CoC,390,152,8,230,217,...,1,0,378,12,233,153,0,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1003,1003,5e52b003ef313cd4b609d378,MI-512,Grand Traverse Antrim Leelanau Counties CoC,228,41,14,173,87,141,...,0,217,11,195,4,0,17,2,10,167
1004,1004,5e52b003ef313cd4b609d379,MI-513,Marquette Alger Counties CoC,84,33,5,46,41,43,...,0,82,2,75,1,0,4,0,4,50
1005,1005,5e52b003ef313cd4b609d37a,MI-514,Battle Creek/Calhoun County CoC,204,41,11,152,64,140,...,0,197,7,108,85,1,1,0,9,102
1006,1006,5e52b003ef313cd4b609d37b,MI-515,Monroe City & County CoC,193,50,14,129,100,93,...,0,182,11,125,61,0,0,0,7,122
1007,1007,5e52b003ef313cd4b609d37c,MI-516,Norton Shores Muskegon City & County CoC,135,29,14,92,51,84,...,0,134,1,59,69,1,1,0,5,108

In [55]:
# homeless2_data = homeless2_data.drop('ida', axis=1)
homeless2_data

,id,_id,CoC Number,CoC Name,CoC Category,Overall Homeless 2019,Overall Homeless - Under 18 2019,Overall Homeless - Age 18 to 24 2019,Overall Homeless - Over 24 2019,Overall Homeless - Female 2019,...,Overall Homeless - Transgender 2019,Overall Homeless - Gender Non-Conforming 2019,"Overall Homeless - Non-Hispanic/Non-Latino, 2019","Overall Homeless - Hispanic/Latino, 2019","Overall Homeless - White, 2019","Overall Homeless - Black or African American, 2019","Overall Homeless - Asian, 2019","Overall Homeless - American Indian or Alaska Native, 2019",Overall Homeless - Native Hawaiian or Other Pacific Islander 2019,Overall Homeless - Multiple Races 2019
0,0,5e52b068ef313cd4b60a1494,MI-518,Livingston County CoC,103,27,14,62,47,56,...,0,101,2,96,3,0,0,0,4,47
1,1,5e52b068ef313cd4b60a1495,MI-519,Holland/Ottawa County CoC,258,96,18,144,120,138,...,0,196,62,176,61,1,2,0,18,103
2,2,5e52b068ef313cd4b60a1496,MI-523,Eaton County CoC,107,60,9,38,59,48,...,0,91,16,92,6,0,0,0,9,32
3,3,5e52b068ef313cd4b60a1497,MN-500,Minneapolis/Hennepin County CoC,3057,1,176,331,1,550,...,404,1,641,9,3,2,853,204,534,1
4,4,5e52b068ef313cd4b60a1498,MN-501,Saint Paul/Ramsey County CoC,1438,376,176,886,576,861,...,0,1,300,138,446,744,48,73,2,125
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,994,5e52b068ef313cd4b60a187f,WV-503,Charleston/Kanawha Putnam Boone Clay Counties CoC,385,45,50,290,115,270,...,380,5,301,74,0,0,0,10,226,37
995,995,5e52b068ef313cd4b60a1880,WV-508,West Virginia Balance of State CoC,1109,136,91,882,379,730,...,1,079,30,913,163,1,9,3,20,597
996,996,5e52b068ef313cd4b60a1881,WY-500,Wyoming Statewide CoC,798,187,59,552,295,503,...,669,129,628,30,0,97,1,42,231,27
997,997,5e52b068ef313cd4b60a1882,,Total,564708,127,787,52,973,383,...,224,344,339,075,1,289,452,140,112,568
998,998,5e52b068ef313cd4b60a1883,,,,,,,,,...,,,,,,,,,,

In [62]:
homeless1_data.dtypes

id                                                                    int64
_id                                                                  object
CoC Number                                                           object
CoC Name                                                             object
CoC Category                                                         object
Overall Homeless 2019                                                object
Overall Homeless - Under 18 2019                                     object
Overall Homeless - Age 18 to 24 2019                                 object
Overall Homeless - Over 24 2019                                      object
Overall Homeless - Female 2019                                       object
Overall Homeless - Male 2019                                         object
Overall Homeless - Transgender 2019                                  object
Overall Homeless - Gender Non-Conforming 2019                        object
Overall Homeless - Non-Hispanic/Non-Latino, 2019                     object
Overall Homeless - Hispanic/Latino, 2019                             object
Overall Homeless - White, 2019                                       object
Overall Homeless - Black or African American, 2019                   object
Overall Homeless - Asian, 2019                                       object
Overall Homeless - American Indian or Alaska Native, 2019            object
Overall Homeless - Native Hawaiian or Other Pacific Islander 2019    object
Overall Homeless - Multiple Races 2019                               object
dtype: object

ValueError: invalid literal for int() with base 10: 'Overall Homeless 2019'